### ISSUE TITLE
Connection with a separate databse

### ISSUE THREAD

**Issue by Teranode** [ELD/bridgevb#4]
can a connection with a separate database be established?
I don't want to have to put both laravel and vbulletin on the same databse

**Comment by ELD** [comment]
You should be able to. If you view the README you'll see the config options. Inside the config you can specify a connection. If it doesn't work, feel free to hack on it and submit a PR, or post back here and I'll try to fix it. 

I do remember testing it way back when I was first developing it, so it should work.

**Comment by ChristianMcQuilkin** [comment]
when it says connection does it mean put in the vbulletin database name?

**Comment by ELD** [comment]
That's actually a good question because my instructions are unclear. Here's quite an extended example that will hopefully answer your question. I'm going to look at this package's config file and the Laravel ```database.php``` configuration file and hopefully I'll make it clear enough about which file we're looking at when.

So to start off, Laravel's default ```database.php``` (full path: ```./app/config/database.php``` config file looks like this:
```php
<?php

return array(

	/*
	|--------------------------------------------------------------------------
	| PDO Fetch Style
	|--------------------------------------------------------------------------
	|
	| By default, database results will be returned as instances of the PHP
	| stdClass object; however, you may desire to retrieve records in an
	| array format for simplicity. Here you can tweak the fetch style.
	|
	*/

	'fetch' => PDO::FETCH_CLASS,

	/*
	|--------------------------------------------------------------------------
	| Default Database Connection Name
	|--------------------------------------------------------------------------
	|
	| Here you may specify which of the database connections below you wish
	| to use as your default connection for all database work. Of course
	| you may use many connections at once using the Database library.
	|
	*/

	'default' => 'mysql',

	/*
	|--------------------------------------------------------------------------
	| Database Connections
	|--------------------------------------------------------------------------
	|
	| Here are each of the database connections setup for your application.
	| Of course, examples of configuring each database platform that is
	| supported by Laravel is shown below to make development simple.
	|
	|
	| All database work in Laravel is done through the PHP PDO facilities
	| so make sure you have the driver for your particular database of
	| choice installed on your machine before you begin development.
	|
	*/

	'connections' => array(

		'sqlite' => array(
			'driver'   => 'sqlite',
			'database' => __DIR__.'/../database/production.sqlite',
			'prefix'   => '',
		),

		'mysql' => array(
			'driver'    => 'mysql',
			'host'      => 'localhost',
			'database'  => 'forge',
			'username'  => 'forge',
			'password'  => '',
			'charset'   => 'utf8',
			'collation' => 'utf8_unicode_ci',
			'prefix'    => '',
		),

		'pgsql' => array(
			'driver'   => 'pgsql',
			'host'     => 'localhost',
			'database' => 'forge',
			'username' => 'forge',
			'password' => '',
			'charset'  => 'utf8',
			'prefix'   => '',
			'schema'   => 'public',
		),

		'sqlsrv' => array(
			'driver'   => 'sqlsrv',
			'host'     => 'localhost',
			'database' => 'database',
			'username' => 'root',
			'password' => '',
			'prefix'   => '',
		),

	),

	/*
	|--------------------------------------------------------------------------
	| Migration Repository Table
	|--------------------------------------------------------------------------
	|
	| This table keeps track of all the migrations that have already run for
	| your application. Using this information, we can determine which of
	| the migrations on disk haven't actually been run in the database.
	|
	*/

	'migrations' => 'migrations',

	/*
	|--------------------------------------------------------------------------
	| Redis Databases
	|--------------------------------------------------------------------------
	|
	| Redis is an open source, fast, and advanced key-value store that also
	| provides a richer set of commands than a typical key-value systems
	| such as APC or Memcached. Laravel makes it easy to dig right in.
	|
	*/

	'redis' => array(

		'cluster' => false,

		'default' => array(
			'host'     => '127.0.0.1',
			'port'     => 6379,
			'database' => 0,
		),

	),

);
```

So if you notice, the connections are arrays and the connection used by default is the one that's the value to the ```default => [VALUE]``` key-value pair. The ```mysql => array(...)``` array should be set to your Laravel DB connection. In order to add the vBulletin database add another array with the connection information. Here's an example of what that might look like:

```php
'vbulletin' => array(
	'driver'    => 'mysql',
	'host'      => 'localhost',
	'database'  => 'vb_db',
	'username'  => 'my_vbulletin_database_username',
	'password'  => 'somepassword',
	'charset'   => 'utf8',
	'collation' => 'utf8_unicode_ci',
	'prefix'    => '',
),
```

So if we put it all together, our ```app/config/database.php``` file would look like:

```php
<?php

return array(

	/*
	|--------------------------------------------------------------------------
	| PDO Fetch Style
	|--------------------------------------------------------------------------
	|
	| By default, database results will be returned as instances of the PHP
	| stdClass object; however, you may desire to retrieve records in an
	| array format for simplicity. Here you can tweak the fetch style.
	|
	*/

	'fetch' => PDO::FETCH_CLASS,

	/*
	|--------------------------------------------------------------------------
	| Default Database Connection Name
	|--------------------------------------------------------------------------
	|
	| Here you may specify which of the database connections below you wish
	| to use as your default connection for all database work. Of course
	| you may use many connections at once using the Database library.
	|
	*/

	'default' => 'mysql',

	/*
	|--------------------------------------------------------------------------
	| Database Connections
	|--------------------------------------------------------------------------
	|
	| Here are each of the database connections setup for your application.
	| Of course, examples of configuring each database platform that is
	| supported by Laravel is shown below to make development simple.
	|
	|
	| All database work in Laravel is done through the PHP PDO facilities
	| so make sure you have the driver for your particular database of
	| choice installed on your machine before you begin development.
	|
	*/

	'connections' => array(

		'sqlite' => array(
			'driver'   => 'sqlite',
			'database' => __DIR__.'/../database/production.sqlite',
			'prefix'   => '',
		),

		'mysql' => array(
			'driver'    => 'mysql',
			'host'      => 'localhost',
			'database'  => 'forge',
			'username'  => 'forge',
			'password'  => '',
			'charset'   => 'utf8',
			'collation' => 'utf8_unicode_ci',
			'prefix'    => '',
		),

		'vbulletin' => array(
			'driver'    => 'mysql',
			'host'      => 'localhost',
			'database'  => 'vb_db',
			'username'  => 'my_vbulletin_database_username',
			'password'  => 'somepassword',
			'charset'   => 'utf8',
			'collation' => 'utf8_unicode_ci',
			'prefix'    => '',
		),

		'pgsql' => array(
			'driver'   => 'pgsql',
			'host'     => 'localhost',
			'database' => 'forge',
			'username' => 'forge',
			'password' => '',
			'charset'  => 'utf8',
			'prefix'   => '',
			'schema'   => 'public',
		),

		'sqlsrv' => array(
			'driver'   => 'sqlsrv',
			'host'     => 'localhost',
			'database' => 'database',
			'username' => 'root',
			'password' => '',
			'prefix'   => '',
		),

	),

	/*
	|--------------------------------------------------------------------------
	| Migration Repository Table
	|--------------------------------------------------------------------------
	|
	| This table keeps track of all the migrations that have already run for
	| your application. Using this information, we can determine which of
	| the migrations on disk haven't actually been run in the database.
	|
	*/

	'migrations' => 'migrations',

	/*
	|--------------------------------------------------------------------------
	| Redis Databases
	|--------------------------------------------------------------------------
	|
	| Redis is an open source, fast, and advanced key-value store that also
	| provides a richer set of commands than a typical key-value systems
	| such as APC or Memcached. Laravel makes it easy to dig right in.
	|
	*/

	'redis' => array(

		'cluster' => false,

		'default' => array(
			'host'     => '127.0.0.1',
			'port'     => 6379,
			'database' => 0,
		),

	),

);
```

By default, Laravel will only use the ```mysql``` connection because it was set as the default option. You can use the vBulletin database by using the ```DB``` facade and the ```connection``` method such as ```DB::connection('my_connection')```.

So in order to use multiple connections in your config file for the package you just need to put your vBulletin database connection in the ```connection => ``` key-value pair.

Hopefully this makes sense. I know my explanation is a little all over the place and I rushed to put it together. Let me know, again, if anything's unclear.

**Comment by ChristianMcQuilkin** [comment]
That seems simple enough

**Comment by ELD** [comment]
Awesome. Glad I could help. I haven't updated the code in this project in quite some time, so things might not work as expected. I've been meaning to update it and re-release it with additional integration with other forum systems (like XenForo, IPB, etc.). Glad you have a use for it.

Let me know if you run across any other issues.

**Comment by ChristianMcQuilkin** [comment]
I mean i get what you meant by input into the database, and i did that, but i had to set things up differently because of dependencies + it's not a project i made and im not really strong on laravel, i just know php and blade template methods. (Basically im a designer and if it's a cms i know it)

So basically what im saying is that when i try to install the package via composer i get some error about dependencies for illumination/support.

What i did then was set the package in app/lib/Authentication/Bridgevb
then in the app.php i had it call:

Provider:
'Lib\Authentication\Bridgevb\BridgevbServiceProvider',

Aliases:
'Bridgevb' => 'Lib\Authentication\Bridgevb\Facades\BridgeVb',

Then ran composer install/update

autoload_classmap.php now has their location:
![gzkmegu](https://cloud.githubusercontent.com/assets/1527149/5980231/8d3d83a6-a87c-11e4-9ede-f74222ac9abc.png)

their namespace are also in that following order

The problem i am now having is where to put the config file.
![covfule](https://cloud.githubusercontent.com/assets/1527149/5980305/1a1be6be-a87d-11e4-9741-16c8991132f9.png)

i dont know where to put them if the Bridge service provider is giving me a location of eld/bridgevb

**Comment by ELD** [comment]
Okay, I see what's happening. The package was set to use Laravel 4.0 and not 4.1 or 4.2 (4.2 is the current version, likely your version). Composer fails to install the package because the version of the framework is newer than is allowed in the package's composer.json file.

I went ahead and updated the composer.json file to allow any version of Laravel 4.0+. So to remedy the issue, undo whatever you've done to try to manually install the package and add the following to your composer.json file:
`"eld/bridgevb": "dev-master"`

This will pull in the master repository's version of the package which contains the updated composer.json. From there, the package should install into the `vendor/` folder and allow you to use it as the README specifies.

Again, let me know if that still doesn't quite work.

**Comment by Denoder** [comment]
now it works :D

**Comment by ELD** [comment]
No problem. Let me know if you need any other assistance. I'm closing the
issue for now.

**Comment by Denoder** [comment]
okay

**Comment by Denoder** [comment]
sorry to ask this but do you have any examples of a login blade? I have one but it uses a session controller, so it logs me in via the session controller not vbulletin.

**Comment by ELD** [comment]
No worries. I don't have an example off-hand, but I can offer a small snippet.

You want to know how one would set up a view to log into vBulletin?

**Comment by Denoder** [comment]
yes please. Most of the activity will be going towards the forum.

**Comment by Denoder** [comment]
What im currently using for authentication is sentry2

**Comment by ELD** [comment]
Right, sorry for the delay. I've been a bit busy the past couple days. To answer your question, there really isn't such a comprehensive way to authenticate like you do in Sentry2. If your login form is intending to authenticate against your vBulletin database then you'd use the `Bridgevb::attempt($creds)` method to pass an array of the credentials. It'll authenticate agains the database and create the proper session (if the user checked the 'Remember Me' box, if one is available). In order to guard routes against non-authenticated users you can use `Bridgevb::isLoggedIn()` to get whether the user is logged in.

I know this isn't a full example, but the example usage in the README will tell you what you need to know. Most of the usage is within controllers, not views. You just need a regular Blade view with a form that posts to the particular controller (which handles the authentication) for it work.

**Comment by Denoder** [comment]
This is what my session controller looks like:
http://pastebin.com/3L40Ap2A

also where do i find: cookie_hash

**Comment by ELD** [comment]
Okay, I see what’s going on now. So first off, Sentry assumes that you’re not using another authentication driver and that your users table exists within your vBulletin database. There might be a way to use Sentry with Bridgevb but it’s not intended to be used in such a way. If you look at the example usage in the README, you can see how to attempt to authenticate a user. It’s relatively simple in comparison to Sentry.  Even though those examples happen within route closures, you can use that code without any issues in any controller.

**Comment by ELD** [comment]
Oh also, just realized I didn't answer your question about the cookie_hash location. It's in the `includes/functions.php` file in your vBulletin installation.

**Comment by Denoder** [comment]
well while i figure that confusion out.
When do you think the IPB integration will be done?

**Comment by ELD** [comment]
I don’t know offhand. I’ve been meaning to rewrite the package to integrate multiple existing forums (such as vB, IPB, XenForo, etc) but I haven’t gotten around to it yet. I wasn’t sure if there was a real need/demand for such a package.

**Comment by Denoder** [comment]
well there is a demand for it but the demand was mainly focused on MyBB and other free Forum software. Other than that people have been hiring via freelancer and some others just decided to write their own forum ( though i dont see much progress).

I think the deman stopped somewhere around in them middle of last year so i don't know what happened.

**Comment by ELD** [comment]
Well, I’ll definitely put a more comprehensive version of this plugin (with better vB integration and potentially IPB and others) on the docket to work on. I’ll start up a new repo when I get further in on the progress. I’ve noticed you follow me now so you should get some notification when that repository goes up.

**Comment by Denoder** [comment]
yea, my goal right now is to get sentry to work with vbulletin. I know how sentry works now since ive researched it for the past few weeks, but the way it was put into this script is different than most examples so its gonna be a challenge.

**Comment by Denoder** [comment]
and plus sentry 3 is a subscription model package >_> - so i cant go into that.

**Comment by ELD** [comment]
That's true. I was lucky enough to get into the Github organization for
Sentry 3 before it went to a paid product. That being said, it's a
standalone with solution and doesn't work with existing with solutions like
vBulletin or IPB.

**Comment by Denoder** [comment]
What if i switched to laravel's authentication drivers? would that work?

**Comment by ELD** [comment]
That depends. How exactly are you using Laravel and vBulletin together right now? Do you have an existing forum and are building a website around it in Laravel?

Also, if you want to take continue the conversation off of Github, feel free to email me at the address listed on my Github account.

**Comment by Denoder** [comment]
You should close this now >_> decided to make my own forum. It seems easier and less expensive and less resource intensive than using another forum that has it's own resource usage.
